Attempt to clarify the note on postgres support
rails/solid_cable pull request #32
Opened 2024-09-17 21:51 UTC by jpcamara

* On twitter, some folks (myself included) were confused about the note and thought it was implying some issue with using this gem with Postgres

* This tries to emphasize first that all three are fully supported. Then it tries to specify a bit more clearly the distinction about the action cable built-in adapter vs solid cable

* Also mentions potentially hitting issues with the payload size, or not wanting the `NOTIFY` command (which may be a problem for some folks using pgbouncer)

2024-09-17 22:30 UTC, npezza93 requested changes
otherwise, looks good

2024-09-17 22:30 UTC, npezza93 commented on README.md
> +> Action Cable already has a [dedicated PostgreSQL adapter](https://github.com/rails/rails/blob/main/actioncable/lib/action_cable/subscription_adapter/postgresql.rb),
We should point to the Rails docs here instead of the code. https://guides.rubyonrails.org/action_cable_overview.html#postgresql-adapter

2024-09-19 14:12 UTC, jpcamara commented
Good call @npezza93 - I just updated it to point at the rails docs instead

2024-09-19 14:24 UTC, npezza93 approved these changes

2024-09-19 14:24 UTC, merged